# Generated by Django 5.2.7 on 2025-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('duracao', models.IntegerField()),
                ('lancamento', models.DateField()),
                ('genero', models.CharField()),
                ('diretor', models.CharField()),
            ],
        ),
    ]
